# Generated by Django 4.1 on 2022-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_is_active_order_is_active_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, verbose_name='Items')),
                ('nom', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('Address', models.CharField(max_length=100, verbose_name='Address')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zip Code')),
                ('date_cmde', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_cmde',),
            },
        ),
    ]
