# Generated by Django 4.1 on 2022-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
