# Generated by Django 4.1 on 2022-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_commande_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=0, max_length=100, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
